"""campaign value

Revision ID: 1f80653b6b95
Revises: f10f13c8b645
Create Date: 2026-05-09 20:49:17.460887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f80653b6b95'
down_revision: Union[str, Sequence[str], None] = 'f10f13c8b645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('min_total_volume', sa.Numeric(precision=78, scale=0), nullable=False))
    op.drop_column('campaigns', 'min_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('min_amount', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'min_total_volume')
    # ### end Alembic commands ###
