"""enrollment update

Revision ID: 52b4edeaf6f8
Revises: 1f80653b6b95
Create Date: 2026-05-10 17:25:29.411342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b4edeaf6f8'
down_revision: Union[str, Sequence[str], None] = '1f80653b6b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('max_recipients', sa.Integer(), nullable=False))
    op.add_column('campaigns', sa.Column('enrolled_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('enrollments', sa.Column('total_volume', sa.Numeric(precision=78, scale=0), server_default='0', nullable=False))
    op.add_column('enrollments', sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_enrollments_campaign_volume', 'enrollments', ['campaign_id', 'total_volume'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollments_campaign_volume', table_name='enrollments')
    op.drop_column('enrollments', 'qualified_at')
    op.drop_column('enrollments', 'total_volume')
    op.drop_column('campaigns', 'enrolled_count')
    op.drop_column('campaigns', 'max_recipients')
    # ### end Alembic commands ###
