"""initial schema

Revision ID: 64955dd29840
Revises: 
Create Date: 2026-05-08 17:44:07.446955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64955dd29840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('start_block', sa.BigInteger(), nullable=True),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'token')
    )
    op.create_table('processed_blocks',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'token', 'block_number')
    )
    op.create_table('protocol_contracts',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('protocol_slug', sa.String(), nullable=False),
    sa.Column('protocol_name', sa.String(), nullable=False),
    sa.Column('protocol_color', sa.String(length=7), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'address')
    )
    op.create_index(op.f('ix_protocol_contracts_protocol_slug'), 'protocol_contracts', ['protocol_slug'], unique=False)
    op.create_table('tokens',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'address')
    )
    op.create_table('wallets',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chain_id', 'address')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('target_contract_address', sa.String(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id', 'target_contract_address'], ['protocol_contracts.chain_id', 'protocol_contracts.address'], ),
    sa.ForeignKeyConstraint(['chain_id', 'token_address'], ['tokens.chain_id', 'tokens.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_active', 'campaigns', ['starts_at', 'ends_at'], unique=False)
    op.create_index('ix_campaigns_chain_target', 'campaigns', ['chain_id', 'target_contract_address'], unique=False)
    op.create_index('ix_campaigns_chain_token', 'campaigns', ['chain_id', 'token_address'], unique=False)
    op.create_table('transfers',
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['chain_id', 'token'], ['tokens.chain_id', 'tokens.address'], ),
    sa.PrimaryKeyConstraint('chain_id', 'tx_hash', 'log_index')
    )
    op.create_index('ix_transfers_chain_cursor', 'transfers', ['chain_id', 'block_number', 'log_index'], unique=False)
    op.create_index('ix_transfers_chain_from_cursor', 'transfers', ['chain_id', 'from_address', 'block_number', 'log_index'], unique=False)
    op.create_index('ix_transfers_chain_to_cursor', 'transfers', ['chain_id', 'to_address', 'block_number', 'log_index'], unique=False)
    op.create_index('ix_transfers_chain_token_cursor', 'transfers', ['chain_id', 'token', 'block_number', 'log_index'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_chain_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['wallet_chain_id', 'wallet_address'], ['wallets.chain_id', 'wallets.address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_chain_id', 'wallet_address', 'campaign_id', name='uq_enrollment_wallet_campaign')
    )
    op.create_index('ix_enrollments_campaign', 'enrollments', ['campaign_id'], unique=False)
    op.create_index('ix_enrollments_wallet', 'enrollments', ['wallet_chain_id', 'wallet_address'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_chain_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['wallet_chain_id', 'wallet_address'], ['wallets.chain_id', 'wallets.address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_chain_id', 'wallet_address', 'campaign_id', name='uq_reward_wallet_campaign')
    )
    op.create_index('ix_rewards_campaign', 'rewards', ['campaign_id'], unique=False)
    op.create_index('ix_rewards_wallet', 'rewards', ['wallet_chain_id', 'wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rewards_wallet', table_name='rewards')
    op.drop_index('ix_rewards_campaign', table_name='rewards')
    op.drop_table('rewards')
    op.drop_index('ix_enrollments_wallet', table_name='enrollments')
    op.drop_index('ix_enrollments_campaign', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_transfers_chain_token_cursor', table_name='transfers')
    op.drop_index('ix_transfers_chain_to_cursor', table_name='transfers')
    op.drop_index('ix_transfers_chain_from_cursor', table_name='transfers')
    op.drop_index('ix_transfers_chain_cursor', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_campaigns_chain_token', table_name='campaigns')
    op.drop_index('ix_campaigns_chain_target', table_name='campaigns')
    op.drop_index('ix_campaigns_active', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('wallets')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_protocol_contracts_protocol_slug'), table_name='protocol_contracts')
    op.drop_table('protocol_contracts')
    op.drop_table('processed_blocks')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
