"""add merkle_roots and reward_claims

Revision ID: 891d8ebf73f1
Revises: db687660daf3
Create Date: 2026-06-23 16:04:54.150591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891d8ebf73f1'
down_revision: Union[str, Sequence[str], None] = 'db687660daf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merkle_roots',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('root_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('set_tx_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_merkle_roots_total_nonneg'),
    sa.CheckConstraint('winner_count >= 0', name='ck_merkle_roots_winner_nonneg'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('reward_claims',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('leaf_index', sa.Integer(), nullable=False),
    sa.Column('proof', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_tx_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_reward_claims_amount_nonneg'),
    sa.CheckConstraint('leaf_index >= 0', name='ck_reward_claims_leaf_nonneg'),
    sa.CheckConstraint('wallet_address = lower(wallet_address)', name='ck_reward_claims_addr_lower'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'wallet_address')
    )
    op.create_index('ix_reward_claims_wallet', 'reward_claims', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reward_claims_wallet', table_name='reward_claims')
    op.drop_table('reward_claims')
    op.drop_table('merkle_roots')
    # ### end Alembic commands ###
