"""add tx_jobs

Revision ID: b3ca31b16f8d
Revises: a11bae4a1710
Create Date: 2026-07-11 01:47:14.933408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ca31b16f8d'
down_revision: Union[str, Sequence[str], None] = 'a11bae4a1710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tx_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('nonce', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('gas_price', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mined_block', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_tx_jobs_attempts_nonneg'),
    sa.CheckConstraint('nonce >= 0', name='ck_tx_jobs_nonce_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tx_jobs_status', 'tx_jobs', ['status', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tx_jobs_status', table_name='tx_jobs')
    op.drop_table('tx_jobs')
    # ### end Alembic commands ###
