"""drop unused rewards table (phase 1 artifact)

Revision ID: deed13027d69
Revises: b3ca31b16f8d
Create Date: 2026-07-30 14:26:26.482003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deed13027d69'
down_revision: Union[str, Sequence[str], None] = 'b3ca31b16f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewards_campaign'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_wallet'), table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet_chain_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=78, scale=0), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('rewards_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['wallet_chain_id', 'wallet_address'], ['wallets.chain_id', 'wallets.address'], name=op.f('rewards_wallet_chain_id_wallet_address_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rewards_pkey')),
    sa.UniqueConstraint('wallet_chain_id', 'wallet_address', 'campaign_id', name=op.f('uq_reward_wallet_campaign'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_rewards_wallet'), 'rewards', ['wallet_chain_id', 'wallet_address'], unique=False)
    op.create_index(op.f('ix_rewards_campaign'), 'rewards', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
